{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik" ) -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: {{ .Release.Namespace }}

spec:
  stripPrefix:
    prefixes:
      - /hello
{{- end }}