{{- with .Values.ingress  -}}
{{- if and .enabled (eq .className "traefik" ) -}}
{{- range .middlewares -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}

spec:
  {{- toYaml .spec  | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end }}