apiVersion: v2
name: world
description: A Helm chart used to deploy the world app
kubeVersion: v1.34.0
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: lypomer
    url: https://github.com/lypomer/